from .users import User as UserResource
from .users import Users as UsersResource
from .books import Book as BookResource
from .books import Books as BooksResource
from .notifications import Notifications as NotificationsResource
from .configuration import Configuration as ConfigurationResource
from .configuration import Configurations as ConfigurationsResource
from .signin import Signin as SigninResource
from .login import Login as LoginResource
from .loans import Loans as LoansResource
from .loans import Loan as LoanResource
from .ratings import Ratings as RatingsResource
from .ratings import Rating as RatingResource
from .authors import Author as AuthorResource
from .authors import Authors as AuthorsResource
from .loans import LoansByUser as LoansByUserResource